### ISSUE TITLE
Add support of Debian Bookworm

### ISSUE THREAD

**Issue by kelson42** [legoktm/gh-action-build-deb#3]
It seems not possible for now, see https://github.com/openzim/libzim/pull/811

**Comment by kelson42** [comment]
@legoktm Any chance add support of bookworm?

**Comment by kelson42** [comment]
@legoktm Has this issue been implemented 2 weeks ago?

**Comment by andy5995** [comment]
Looks like it: https://github.com/legoktm/gh-action-build-deb/tree/debian-bookworm (bookworm branch)

**Comment by kelson42** [comment]
Fixed
